# Generated by Django 2.2.12 on 2021-06-16 16:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_main_group', to='otree.Session')),
            ],
            options={
                'db_table': 'trivia_main_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trivia_main_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'trivia_main_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('question_id', otree.db.models.StringField(max_length=10000, null=True)),
                ('question_text', otree.db.models.StringField(max_length=10000, null=True)),
                ('question_solution', otree.db.models.StringField(max_length=10000, null=True)),
                ('question_type', otree.db.models.StringField(max_length=10000, null=True)),
                ('question_choice_1', otree.db.models.StringField(max_length=10000, null=True)),
                ('question_choice_2', otree.db.models.StringField(max_length=10000, null=True)),
                ('question_choice_3', otree.db.models.StringField(max_length=10000, null=True)),
                ('question_choice_4', otree.db.models.StringField(max_length=10000, null=True)),
                ('round_total', otree.db.models.FloatField(default=0, null=True)),
                ('round_payout', otree.db.models.FloatField(default=0, null=True)),
                ('my_chat_joint', otree.db.models.StringField(max_length=10000, null=True)),
                ('chat_content_joint', otree.db.models.StringField(max_length=10000, null=True)),
                ('my_chat_results', otree.db.models.StringField(max_length=10000, null=True)),
                ('chat_content_results', otree.db.models.StringField(max_length=10000, null=True)),
                ('blur_count_private', otree.db.models.IntegerField(default=0, null=True)),
                ('blur_count_joint', otree.db.models.IntegerField(default=0, null=True)),
                ('idle_private', otree.db.models.IntegerField(default=0, null=True)),
                ('idle_joint', otree.db.models.IntegerField(default=0, null=True)),
                ('time_spent_on_page_private', otree.db.models.FloatField(null=True)),
                ('time_spent_on_page_joint', otree.db.models.FloatField(null=True)),
                ('trial_counter', otree.db.models.IntegerField(default=0, null=True)),
                ('is_inactive', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('submitted_answer_private', otree.db.models.StringField(max_length=10000, null=True)),
                ('submitted_answer_joint', otree.db.models.StringField(max_length=10000, null=True)),
                ('confidence_private', otree.db.models.IntegerField(null=True, verbose_name='How confident do you feel in this answer, prior to discussing with your partner?')),
                ('confidence_joint', otree.db.models.IntegerField(null=True, verbose_name='How confident do you feel in this answer now that you have discussed with your partner?')),
                ('total_score', otree.db.models.FloatField(default=0.0, null=True)),
                ('rescue_event', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('drag_down', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('corrected_private', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('uncorrected_private', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('cheat_consent', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia_main.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_main_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_main_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_main.Subsession')),
            ],
            options={
                'db_table': 'trivia_main_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_main.Subsession'),
        ),
    ]
