# Generated by Django 2.2.12 on 2021-06-16 16:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endline_scrabble_group', to='otree.Session')),
            ],
            options={
                'db_table': 'endline_scrabble_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endline_scrabble_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'endline_scrabble_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('performance', otree.db.models.IntegerField(null=True, verbose_name='How well to you think you and your partner did? Out of 100 random teams completing this study, how do you think you and your partner would rank, with 1 as the highest rank and 100 the lowest?')),
                ('typicality', otree.db.models.FloatField(null=True)),
                ('worked_well', otree.db.models.FloatField(null=True, verbose_name='To what extent do you agree with the following statement: My partner and I worked well together (0 represents that you strongly disagree, 100 represents that you strongly agree).')),
                ('enjoy', otree.db.models.FloatField(null=True, verbose_name='How much did you enjoy playing with your partner? (0 representing that you strongly disliked it, 100 representing that you strongly enjoyed it)')),
                ('happy_same', otree.db.models.FloatField(null=True, verbose_name='If given the opportunity to play this game again, how happy would you be playing with the same partner? (0 representing very unhappy, 100 representing very happy)')),
                ('partner_valued_me', otree.db.models.FloatField(null=True, verbose_name='To what extent do you agree with the following statement: I feel that my partner valued me and the contributions that I made.  \n            A score of "0" indicates "Disagree Strongly."  A score of "100" indicates "Agree Strongly.')),
                ('i_valued_partner', otree.db.models.FloatField(null=True, verbose_name='To what extent do you agree with the following statement: I valued my partner and the contributions that he or she made.  \n            A score of "0" indicates "Disagree Strongly."  A score of "100" indicates "Agree Strongly.')),
                ('partner_respects_me', otree.db.models.FloatField(null=True, verbose_name='To what extent do you agree with the following statement: I think my partner has respect for people like me.  \n            A score of "0" indicates "Disagree Strongly."  A score of "100" indicates "Agree Strongly.')),
                ('i_respect_partner', otree.db.models.FloatField(null=True, verbose_name='To what extent do you agree with the following statement: I have respect for people like my partner.  \n            A score of "0" indicates "Disagree Strongly."  A score of "100" indicates "Agree Strongly.')),
                ('partner_responsible_success', otree.db.models.FloatField(null=True, verbose_name='To the extent that you succeeded as a team, how much of this success would you say your partner is responsible for? A score of 0 indicates that you would\n            have done just as well without your partner, whereas a score of 100 indicates you were very dependent on your partner.')),
                ('perfect_partner_age', otree.db.models.IntegerField(null=True, verbose_name='Perfect Partner Age: If given the opportunity to play this game again with a partner of your choosing, \n            what would their ideal age be?')),
                ('perfect_partner_sex', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10000, null=True, verbose_name='Perfect Partner Gender: If given the opportunity to play this game again with a partner of your choosing, \n            would they be male or female?')),
                ('perfect_partner_politics', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Perfect Partner Politics: If given the opportunity to play this game again with a partner of your choosing, how strongly liberal or conservative would they be (0 representing strongly liberal, 100 representing strongly conservative)?')),
                ('feelings_thermometer_repub', otree.db.models.FloatField(null=True, verbose_name="We'd again like to get your feelings toward REPUBLICANS in the U.S. on a 'feeling thermometer.' A rating of zero degrees means you feel as cold and negative as possible. A rating of 100 degrees means you feel as warm and positive as possible. You would rate the group at 50 degrees if you don’t feel particularly positive or negative toward the group.  How do you feel about Republicans?")),
                ('feelings_thermometer_democrat', otree.db.models.FloatField(null=True, verbose_name="We'd again like to get your feelings toward DEMOCRATS in the U.S. on a 'feeling thermometer.' A rating of zero degrees means you feel as cold and negative as possible. A rating of 100 degrees means you feel as warm and positive as possible. You would rate the group at 50 degrees if you don’t feel particularly positive or negative toward the group.  How do you feel about Democrats?")),
                ('meta_feelings_thermometer_repub', otree.db.models.FloatField(null=True, verbose_name='Using the same "feelings thermometer", how do you think the average REPUBLICAN feels towards DEMOCRATS in the U.S.?')),
                ('meta_feelings_thermometer_democrat', otree.db.models.FloatField(null=True, verbose_name='Using the same "feelings thermometer", how do you think the average DEMOCRAT feels towards REPUBLICANS in the U.S.?')),
                ('repub_good_for_country', otree.db.models.FloatField(null=True, verbose_name='To what extent do you agree with the statement: "The Republican Party’s policies are good for the country?"\n    A "0" means you Very Strongly Disagree. A rating of "100" means you Very Strongly Agree ')),
                ('dem_good_for_country', otree.db.models.FloatField(null=True, verbose_name='To what extent do you agree with the statement: "The Democratic Party’s policies are good for the country?"\n    A "0" means you Very Strongly Disagree. A rating of "100" means you Very Strongly Agree ')),
                ('immigration_pers', otree.db.models.FloatField(null=True, verbose_name="Immigration: On a scale from 0-100, with 0 representing 'Strongly Disagree' and 100 representing 'Strongly Agree': To what extent do you believe that illegal immigration is a serious problem, and that we should have stricter vetting processes and stronger border control?")),
                ('income_inequality_pers', otree.db.models.FloatField(null=True, verbose_name="Income Inequality: On a scale from 0-100, with 0 representing 'Strongly Disagree' and 100 representing 'Strongly Agree': To what extent do you believe that income inequality is a significant problem in the United States?")),
                ('global_warming_pers', otree.db.models.FloatField(null=True, verbose_name="Global Warming: On a scale from 0-100, with 0 representing 'Strongly Disagree' and 100 representing 'Strongly Agree':To what extent do you agree that global warming is a significant problem in the United States?")),
                ('guncontrol_pers', otree.db.models.FloatField(null=True, verbose_name="Gun Control: On a scale from 0-100, with 0 representing 'Strongly Disagree' and 100 representing 'Strongly Agree': To what extent do you agree that we need more, rather than less, gun control regulation in the United States?")),
                ('racism_pers', otree.db.models.FloatField(null=True, verbose_name="Racism: On a scale from 0-100, with 0 representing 'Strongly Disagree' and 100 representing 'Strongly Agree': To what extent do you believe that racism against minorities is a serious problem in the United States?")),
                ('islam_pers', otree.db.models.FloatField(null=True, verbose_name="Islam and Terrorism: On a scale from 0-100, with 0 representing 'Strongly Disagree' and 100 representing 'Strongly Agree': To what extent do you believe the United States should do more to stop the spread of Islamic terrorism abroad and in the United States?")),
                ('demand_effects', otree.db.models.LongStringField(null=True, verbose_name='What do you think the goal of this experiment is?')),
                ('feedback', otree.db.models.LongStringField(null=True, verbose_name='Do you have any feedback for us?  Did you enjoy the experiment?  Any complaints? What should be changed?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='endline_scrabble.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endline_scrabble_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endline_scrabble_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endline_scrabble.Subsession')),
            ],
            options={
                'db_table': 'endline_scrabble_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endline_scrabble.Subsession'),
        ),
    ]
