# Generated by Django 2.2.12 on 2021-06-16 16:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('team_id', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know_your_partner_group', to='otree.Session')),
            ],
            options={
                'db_table': 'know_your_partner_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='know_your_partner_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'know_your_partner_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('politics', otree.db.models.StringField(choices=[('Republican', 'Republican'), ('Democrat', 'Democrat')], max_length=10000, null=True)),
                ('political_views', otree.db.models.StringField(choices=[('Very Liberal', 'Very Liberal'), ('Mostly Liberal', 'Mostly Liberal'), ('Somewhat Liberal', 'Somewhat Liberal'), ('Moderate', 'Moderate'), ('Somewhat Conservative', 'Somewhat Conservative'), ('Mostly Conservative', 'Mostly Conservative'), ('Very Conservative', 'Very Conservative')], max_length=10000, null=True)),
                ('superpower', otree.db.models.StringField(choices=[('Invisibility', 'Invisibility'), ('Super Strength', 'Super Strength'), ('Ultra High Intelligence', 'Ultra High Intelligence'), ('Flight', 'Flight')], max_length=10000, null=True)),
                ('season', otree.db.models.StringField(choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=10000, null=True)),
                ('fruit', otree.db.models.StringField(choices=[('Pineapple', 'Pineapple'), ('Mango', 'Mango'), ('Blueberry', 'Blueberry'), ('Banana', 'Banana')], max_length=10000, null=True)),
                ('vacation', otree.db.models.StringField(choices=[('Mountains', 'Mountains'), ('Forest', 'Forest'), ('Beach', 'Beach'), ('City', 'City')], max_length=10000, null=True)),
                ('treatment_condition', otree.db.models.StringField(max_length=10000, null=True)),
                ('total_waiting_time', otree.db.models.FloatField(null=True)),
                ('payment_for_wait', otree.db.models.FloatField(null=True)),
                ('number_incorrect_submissions', otree.db.models.IntegerField(default=0, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='know_your_partner.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know_your_partner_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know_your_partner_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='know_your_partner.Subsession')),
            ],
            options={
                'db_table': 'know_your_partner_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='know_your_partner.Subsession'),
        ),
    ]
