# Generated by Django 2.2.12 on 2021-06-16 16:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('team_id', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know_your_partner_new_group', to='otree.Session')),
            ],
            options={
                'db_table': 'know_your_partner_new_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='know_your_partner_new_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'know_your_partner_new_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('partner_politics', otree.db.models.StringField(max_length=10000, null=True)),
                ('partner_political_views', otree.db.models.StringField(max_length=10000, null=True)),
                ('partner_superpower', otree.db.models.StringField(max_length=10000, null=True)),
                ('treatment_condition', otree.db.models.StringField(max_length=10000, null=True)),
                ('number_incorrect_submissions', otree.db.models.IntegerField(default=0, null=True)),
                ('kyp_politics', otree.db.models.StringField(choices=[('Republican', 'Republican'), ('Democrat', 'Democrat')], max_length=10000, null=True, verbose_name='As of today, does your partner lean more to the Republican Party or more to the Democratic Party?')),
                ('kyp_superpower', otree.db.models.StringField(choices=[('Invisibility', 'Invisibility'), ('Super Strength', 'Super Strength'), ('Ultra High Intelligence', 'Ultra High Intelligence'), ('Flight', 'Flight')], max_length=10000, null=True, verbose_name='Which of the following superpowers would your partner most prefer to have?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='know_your_partner_new.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know_your_partner_new_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='know_your_partner_new_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='know_your_partner_new.Subsession')),
            ],
            options={
                'db_table': 'know_your_partner_new_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='know_your_partner_new.Subsession'),
        ),
    ]
