# Generated by Django 2.2.12 on 2021-06-16 16:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_scrabble_group', to='otree.Session')),
            ],
            options={
                'db_table': 'baseline_scrabble_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseline_scrabble_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'baseline_scrabble_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('checkslider', otree.db.models.IntegerField(blank=True, null=True)),
                ('turkID', otree.db.models.StringField(max_length=10000, null=True)),
                ('sex', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10000, null=True)),
                ('birth', otree.db.models.IntegerField(null=True)),
                ('turk_experience', otree.db.models.IntegerField(null=True)),
                ('mturker_loyalty', otree.db.models.StringField(choices=[('1 - Not at all', '1 - Not at all'), ('2', '2'), ('3 - Some amount', '3 - Some amount'), ('4', '4'), (' 5 - Very Much', ' 5 - Very Much')], max_length=10000, null=True)),
                ('dividing_money', otree.db.models.StringField(choices=[('1 - Never', '1 - Never'), ('2', '2'), ('3 - Sometimes', '3 - Sometimes'), ('4', '4'), (' 5 - Very Often', ' 5 - Very Often')], max_length=10000, null=True)),
                ('trust_daily', otree.db.models.StringField(choices=[('1 - Very Little', '1 - Very Little'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7 - Very Much', '7 - Very Much')], max_length=10000, null=True)),
                ('zip_code', otree.db.models.StringField(max_length=10000, null=True)),
                ('race', otree.db.models.StringField(choices=[('White', 'White'), ('Black or African American', 'Black or African American'), ('Asian', 'Asian'), ('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Native Hawaiian or Pacific Islander', 'Native Hawaiian or Pacific Islander')], max_length=10000, null=True)),
                ('education', otree.db.models.StringField(choices=[('Less than High School', 'Less than High School'), ('H.S. Graduate', 'H.S. Graduate'), ('Some College', 'Some College'), ("Associate's Degree", "Associate's Degree"), ('College Graduate', 'College Graduate'), ("Master's Degree", "Master's Degree"), ('Professional Degree (JD/MD), PhD', 'Professional Degree (JD/MD), PhD')], max_length=10000, null=True)),
                ('hispanic', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True)),
                ('politics', otree.db.models.StringField(choices=[('Republican', 'Republican'), ('Democrat', 'Democrat')], max_length=10000, null=True)),
                ('political_views', otree.db.models.StringField(choices=[('Very Liberal', 'Very Liberal'), ('Mostly Liberal', 'Mostly Liberal'), ('Somewhat Liberal', 'Somewhat Liberal'), ('Moderate', 'Moderate'), ('Somewhat Conservative', 'Somewhat Conservative'), ('Mostly Conservative', 'Mostly Conservative'), ('Very Conservative', 'Very Conservative')], max_length=10000, null=True)),
                ('political_views_granular', otree.db.models.FloatField(null=True)),
                ('politics_today', otree.db.models.StringField(choices=[('Strong Democrat', 'Strong Democrat'), ('Weak Democrat', 'Weak Democrat'), ('Strong Republican', 'Strong Republican'), ('Weak Republican', 'Weak Republican'), ('Independent', 'Independent')], max_length=10000, null=True)),
                ('income', otree.db.models.StringField(choices=[('Less than $10,000', 'Less than $10,000'), ('$10,000 to $19,999', '$10,000 to $19,999'), ('$20,000 to $29,999', '$20,000 to $29,999'), ('$30,000 to $39,999', '$30,000 to $39,999'), ('$40,000 to $49,999', '$40,000 to $49,999'), ('$50,000 to $59,999', '$50,000 to $59,999'), ('$60,000 to $69,999', '$60,000 to $69,999'), ('$70,000 to $79,999', '$70,000 to $79,999'), ('$80,000 to $89,999', '$80,000 to $89,999'), ('$90,000 to $99,999', '$90,000 to $99,999'), ('$100,000 to $149,999', '$100,000 to $149,999'), ('$150,000 or more', '$150,000 or more')], max_length=10000, null=True)),
                ('trump', otree.db.models.FloatField(null=True)),
                ('obama', otree.db.models.FloatField(null=True)),
                ('repub_good_for_country', otree.db.models.FloatField(null=True)),
                ('dem_good_for_country', otree.db.models.FloatField(null=True)),
                ('feelings_thermometer_repub', otree.db.models.FloatField(null=True)),
                ('feelings_thermometer_democrat', otree.db.models.FloatField(null=True)),
                ('meta_feelings_thermometer_repub', otree.db.models.FloatField(null=True)),
                ('meta_feelings_thermometer_democrat', otree.db.models.FloatField(null=True)),
                ('immigration_pers', otree.db.models.FloatField(null=True)),
                ('income_inequality_pers', otree.db.models.FloatField(null=True)),
                ('global_warming_pers', otree.db.models.FloatField(null=True)),
                ('racism_pers', otree.db.models.FloatField(null=True)),
                ('islam_pers', otree.db.models.FloatField(null=True)),
                ('guncontrol_pers', otree.db.models.FloatField(null=True)),
                ('superpower', otree.db.models.StringField(choices=[('Invisibility', 'Invisibility'), ('Super Strength', 'Super Strength'), ('Ultra High Intelligence', 'Ultra High Intelligence'), ('Flight', 'Flight')], max_length=10000, null=True)),
                ('season', otree.db.models.StringField(choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=10000, null=True)),
                ('fruit', otree.db.models.StringField(choices=[('Pineapple', 'Pineapple'), ('Mango', 'Mango'), ('Blueberry', 'Blueberry'), ('Banana', 'Banana')], max_length=10000, null=True)),
                ('vacation', otree.db.models.StringField(choices=[('Mountains', 'Mountains'), ('Forest', 'Forest'), ('Beach', 'Beach'), ('City', 'City')], max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseline_scrabble.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_scrabble_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_scrabble_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseline_scrabble.Subsession')),
            ],
            options={
                'db_table': 'baseline_scrabble_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseline_scrabble.Subsession'),
        ),
    ]
